set-option -g prefix C-a
# Send C-a to nested tmux sessions or apps that need it
bind-key C-a send-prefix

set-option -g mouse on

# True 24-bit color support
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

set-option -g history-limit 10000

# To please our lord neovim
set -sg escape-time 0
set -g focus-events on

set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

# Vi-style copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes and keep the current working directory
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
# Also keep cwd when opening a new window
bind-key c new-window -c "#{pane_current_path}"


bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded!"
